//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeRestaurant.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestaurantEntities : DbContext
    {
        public RestaurantEntities()
            : base("name=RestaurantEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLCategori> TBLCategori { get; set; }
        public virtual DbSet<TBLNote> TBLNote { get; set; }
        public virtual DbSet<TBLProduct> TBLProduct { get; set; }
        public virtual DbSet<TBLTable> TBLTable { get; set; }
        public virtual DbSet<TBLUser> TBLUser { get; set; }
        public virtual DbSet<TBLBasket> TBLBasket { get; set; }
        public virtual DbSet<TBLOrderDetail> TBLOrderDetail { get; set; }
    }
}
