//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeRestaurant.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLNote
    {
        public int ID { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
