//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeRestaurant.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLOrderDetail
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Piece { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Payment { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    }
}
